travis:
  secure:
    BINSTAR_TOKEN: FPIpl9swaNA32oimWJa1/nS5gSGfeFEj+ETO//5ahEtnjDVXdAhIjrrD+nqYCRNkIE9NEZDjvL7ZQzq5DHwoZUX94w0udewtsa+qZS4s9joVWP9e+yJHM4ksW0MGqYjJ8z+3gkzdZK/C8WNxjQLAkFjWWNWjlMhJ3+bmBnGRVOQliqHn/tpzSd1OO3xeXpX0cI2Ttj0Wp6ANKvTaxWzyiJoA+BGlHxzNZHksHkxKXjqwAc20pvGTEdUfbDoCpWjPgRvkWQ5WIPW5wtoBv0P1kx1rwViqSw82HwP2N0LLI0TfcgtEVgEbW315KKAo3VWdpxOHd/Qqjbvvu++CCgqzgTdlw2IzCm3A5cBCKenjeiZsKivSujeW9TNDlcsOfORmXQkTJcRmFy4bXckccjNinklMKqAY6J4ewTzEKphuLZZBy36Di2joc7TVuvkXcnPdUMpd4QmLAzsSh96YeasdHSLQYrZM9xnLG2pmc1rAejluBb0EJF+HvxB5PxJrAnLX5r6SyAqcqfGgnCTbb+RISE0kBMBjyj2r15ZJ7TByxm7n53fWasrv57gwyvzSBYdkE44XN8P7tUudlwIaELSZCFFswEa3wqAWi3+aF/lu1vSAcfnX+jLL+feQE2linpxsTnOlIQG60thY9ngzC5WRQA0V7bbkmdc2/fIoEXTZ+yw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
