travis:
  secure:
    BINSTAR_TOKEN: HuvA+fRjAMZxkoNwdOjuxHjfhO5mhOhnuGlb9MKo5bijDJJP6v8WuefGy7ubvmQAcLvRF2qxJ/DHz/JBzcllPUSux085657PlhfHw0LOOCuoby/QLfmppQ+aEAcfHWihUBhhgXTnOwSCVan8o8CCN/r/P6jZ22rVyaRRV2+8s4dM4g4ZafpC7frpuqyxunprrTvwpXl1y630e6TMZq0wsYAhjccUplip6movgK/Fm5wgmGtK8+yX2yqMbH58cWZFwLTLSOVIFgb5Jn12iR4Qp+JNtOY9+QtfoEl/JW3+hkcqn9SD6DA9mEg1qXLC0sEjKlwDe96v9EJwlHiSHcwvN86z6cH8Q86xEWBbWUf/GXilIZLgYyCx+ZU1FdEVSqcjzjSblP3wYyr6u+4/y090vJXMPOvWIEZ0HrNt/iYAHFTF0dveUjwZcvFYqZE4XAv3OoZnRc2yh1EC2Tf2jLVerdkwD02en2GlUK+RXzwzJducPIQSGBKjnGIfrH4vAyivgn1t8+hocvOFgmS5ug86QYxs3RDWOAXF/hWuAEbTpH+EnsZk5Pqu/FAkfcLJffBpzQtVUHF7xc309HZkZiF7e1ew0kqOZzr0Mm2XZy3q5GsvnGFuCIgedHvkuCCb6F/8rVfHsWEiSfpsTKYMtoVeqXNGar+wMWDCMmCfUOYLT7I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
