travis:
  secure:
    BINSTAR_TOKEN: dygDfMC7EBKesZ/elTyLsK+IbHeMKtbsnBJFQJypgJby9r11LaRrB74Ng/VaVkenPabAM34Sem6A6Auh+HDypvrZFEGul5KsKbGkZ22PBcNXWnEHMUUVS4fHYT2eOUeTKbsDANdc6AX+3085y4yqYG2x9Kz4OPXDaEyTPQkOwaGIfIcOc3K0BQovXDsS6aaim5AOAN21tCsnDUzUUFckNmPZGJgaWCMxWnAHARp7KJP1bHGxqrfeXnwZe6AtNLWXKb4g0I0nwHKtsU3uPaWmEQ03lhsbzg64/l2QTYuNbMMK7iw7LmoafwhGcgYfacdSQHN8V4ODrIMWJVG6h6cfTdtT8l4hGmnExdJ8lsyZ2UN+PXIKGQ0jnWY0looHDDcNyZUuih4yt0LkbELoJycsnz0f8YS2FYKh1nL9iLEUhHmcsm6rk3rTVKPmeYH9rUES1yEMEdqhYcVnZOmymd4zf7NXWIWoObBfXlw5CFYZ0yRUkqrYgcNuQpScPrEBeErO9ByIYBToh6BzgcyGi/CylH0B+fMF/EcVmh0Hy6qBAT1nYNT7lYrxihI82965LjN2OJqAZu4XvLPJxQD832i30hyhrQLXBjw7FTQyZ3xgsWh60x6WSDJKbU9kAEe58oR328+rkvzn0Q1YOGPop+yza/Ng3sXEU/m+9Yz5loH5hag=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
