travis:
  secure:
    BINSTAR_TOKEN: DQ7jLr+9Yz+3Nnd+MfJJXrJ8LCeo5FUhCpO0q5T+OVPmCUgFXWLaJ1Y6B7F3oHcUwE4wx1Zql20MXxlE40yQz0BJYcAmrnaHi5VPiyS1U6XAdQ6zLG95f+6b5ZYlgNA8r55gqLcsmqkJ2eKVoUTMHKeCSme2NKHgP58N/kqXe7EKddRwTAC2wg1k+sxP3eFEIsSkGIK6DdWFgjQmqvkX7ah0XFec6NxNMTRxYFk8vlD+aWosrSSghy7wCgqkkn1S+qzueZtpa72PEoh1UKJgjYa2OmxKPnw5zi3YaaLdLtefx6QJdWUZ5ySCD/VLZ1xQX0tTeSAp+wL1qTRWJIXXFhRxgzZEgp4JzgbEtnLamx0e0mUlpK0jxeEmbwzLMSHgbe5oqMyqC0CFEvVczTsdtekEQNkd/8wg0yIoXGbmsGRU6hVESkmMDcwrv9XrgiwAxsGaiz2iG4CvtPRxYHhxlPTPRI+QkPSx7MsuWfnje3HhE0NFKS9GTsZrOWiUn/vUjbfXfeOXQfKA9+hby0hC1hT5D3b8Ym0sy04eBi1fXK2SPcJhPSIyOd+YQuiV+KOD8ooEhKlwjuNQ0QiTt/vsmpBPYK0RaZxTouG4O9AN5Iu8KwqKvN6zHZWa16JjfLk61U1jfQf78TivvFLElSM6/U26y+E78zIqbXC90/iB9IQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
