travis:
  secure:
    BINSTAR_TOKEN: K8q5pemV2oD/X1qVojgA9E8dgzN6TAQ7V+0FFtPjSisMjp7n6zEw3TdCPeLrc72h/xgUQ/BE6JkCUU7yrwR1oxOCifK6odpmNvz5qlpIzRnYSroUwwY/Dz9L4b1+XHq/fShDE3eDlwuqw3OxFS5syJy6zgNBJjzrp/tAoIcGe6cZUilQ/cMmPtgUWvEeinm5UGEP3ZA51TlnIdyPkmrMC3oLNO4DPt5Qz1+Um7toPwTDm/o//FQIcSZfABEddhcjoK8WhgU1fVNqy6go4/exjLUPSppVXGI+FnvxsLg8qIV8I5lwBNxah7XxHDVfyKqHfaB5RfP99K6VZd/+LX+Rz/MfXonbpRzjDSzY/pj/U7gb/B1e8doP6eegWXq11MaU9XKMtqrLL99gdiDuJ61xZ5wBallgZyBwhH90SdjRPB3o79m5wgfOzh7n3n2gjqdUrFEsuWvJ5Wl7jKU/1qYAYPsnzlNijXZ9e/jj11tto8ie1Ipc7TQ07IyNBfls5VzUWmxAVtTJljDNBzAihCgOQFY3Onl4eceBD0KtNKthgJQi60+FTiEwjhrD7fSZ4cvmFwpSuc1wiFTWszjlDj4vInRCxu6gQHZ+WprGZz43MSP537ZXO2DIZArbCft6P060WFe+f9lK/l5dIEPU2hZkZj+3uIfH169MCYNjtUti+gg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
