travis:
  secure:
    BINSTAR_TOKEN: IdernOF3hl8ai4Xlrh4LfKk2J+ihCfdgyMfD4C3oxYmBgVmgJ+N/WAis7WE3xgarUhaNvAzxj1ORaabqC2vPC9bSfOLLHvt0wZbrtGnbzqnxXU/Tp1puDNOXmRslLs86W/tj84XyOdvxeL45ksgxnSaXU3DZwZsrzRWHe62KaM3vceBzhttx1pUP5B6WVpqtp+r5+8Fijc4gf2bNNdqK3uTZjwy64XNsvUgPezrBhXPJ0Nj2DPIpSVIJdHBIze8+9AbN1sgNktrZIr7pRVjDF9IUMFBHwdgGyR9XNBf9sJ1oaXURr6b+twZUmWUjzApeKvl8I057cP2e9I5qFddgckI45X+RTRufeGSvX59pKgBRMSusHcXGS+K9952y9fKcTyebb0GjnxIvjb0MMzOGZL/+Mp23CHqGDvw3UEXGc1483ZeSqmfVK3vciIGCv8p+tPMUlSu+PHNU602vGpOLWlRAatu+0J2R5TV7+f56n6xzJ1VSu7P1xmci35pCGVI5dbrwc0EkEvRlonJC5bGL/5cHH+ZDNtFq6fewd2uvxdN/g3C5h/n4KOEKvbALTTj7TEi7ACaPJsHIC0cybWRGy2tge1S0NYFywXLe5ICWo4Ti5ZlDDRMABUnlbgsSHhKkBGDMAmmMS2w++jLV3Z4u1QZvkLdX7SIq2Qdy2kDimh0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
