travis:
  secure:
    BINSTAR_TOKEN: RubV4d5nCtsK6gTCnjBJkK/VL1v5tuV/izcysIEwwM874It8lEmMlnboqK/tHjQWUFifZ1oHS37nVAnN4JVAc5A+gNuqWKObH02fJ7Uy5HVPIQe9WDd6+wi2L9Kpu1DtDhNlvvRsJ1BllOIj4swoL860WwUEv/TQA+nLAWmlXazy9CwcPcYL5CbDWvjVPZfpqYOCKBic0r8Frxg3MO3FOVj3K+vP7GUvwwmLUAws2lbfMxd3jieBXxOTSKE4V80JWNpxOkb5iMYp7EgxpbQF6SJp6EOeleRbYc0DswIgvwOSawhQNVbpB5BY4cSYldkf3UKZ766EX0SMZ8FEqZQ3Zd6NPr9bF15RGxkF//crXbUp0qEi0YbeHu+zIc8TczD8AkyG7Z82j78nJ+tAcbON94yzRO9rkEmZ/LV0Ftihj3QlpOC0NOFDNYQXO0pukT8f9xglN02tfUQa3Uc8o7/2jpA//HPXNG97zx4jmIFVyz+hP0coTxl+F0XL3lBTcnFB0ArMIQCullF/2hy1hDUtQ1/TLrsh0MDxgKf6FELl3G7ZZ0+E0w5jbPt5VWIP6PXdnSVwYl/E8MsG89hOPv/MoxHhpqfmoUSIafZco3c0rqgqgkcQe2PgDO0KZitzhoc931YRaAgxbvWCJBOE6gB4p/ZLhze5ATi51W/d/2wjPzk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
