travis:
  secure:
    BINSTAR_TOKEN: IEvc6GnjNtBdU6HWQ6WvivFnelEaSVVUtfZ5OscWgWqwcWB+JRtT8BDIMHlnFwqcnSijXI/6WSgknA7oLzRNhJDj4WwqtMQdm472TBkuVd6CyVxXLuFE1to/rA1CgTgwEtz5yFh3M+go0KPMoOoCnTiqBm62Ejgm136UuRy/q5V+igrrEh9PHxDi4gnbqZ00JloGJ0Kat+7KrjWa4pI+ErPRO0vOCqyJDrTURnT1GM5rhY9oCJGYAShoU12qU/xLPEhWBomxAiVQ3RuX45g9TV9LJ3s5pcAe44nUaOiNTJvZWJ+q+iw22ORVaZlMSqkkTi7KHt1WRfYi3D9gIs5oclzOV7cbmsQqWbu8BR2cqPQ4PZ42bhlfwlUfZB858+HOI8tdomPr4/LjYD0zwVCE4+oN5pXIUBvhEf206iWVZYeK7Plbl22BVXu9PwdxkV2h8BoaP0irFswyuXTailqOUHuk/q2Hx4kAhEy0bZPAgfpHw4rAoJ7bbLEQdX5oJiryaqMz+igOnoMRDXVyzWrBIvr76B1oA4rQlDlC1lhDJwh6VVUXDwVRn0+uIXESi0/B9PnYUoURQ2P/+yu6fVrVjL26a2U3aR7sfTYiRIRxfg8sLPLq9xSJvkru4L3vegn8VKwSwA6gnlCSIjRZpyPGj95Q/imA2UAe8FpmSwvaJYE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
