travis:
  secure:
    BINSTAR_TOKEN: eC4cuOT6HxbtC68wDo3n4KuS0NMg2vj9U2BiHOA88u+BlGgY0O7ArH+JCF/qmu8CbuNxiAHEBe2gTjW3+UmkdMAq9XOv25WZZtsyWM9PLCHKGc7tvuwYDSLoRTSl6kK+JhmtN60c+EnC0f6Q8OnSJ2wgnmvIPaWFCBPKXzK/KcuxNdu9js40yZcN3iStWZdx4Rbry25mz8NRclhQwyD8NoPmNUfd8KEdrvuoeEDg/JIbCdt36vXfMyTlN5A00M25oKrMut3x1w4yv2cxGpv9XIr5T0X/cNOUzJD0PGiMeBImlw0t6axKL9jLfWosatCIsP2O1IOQTyhxBrunnLWO3HKjybahAehJi2Yh/oRqyXqzPDETCX8Uob8UsDdfT3fgYIHSwAhILnFL0wVqD4rdGUFCtz/LDbfhAjWN/UjzMDueX+Oc0E7loqnnEqUac/LoFnz01HqoW3QL2mRnNsCs3/1gHOmSaRklkBhcKdeb9IaFxEYM20CXtYsDIT7OYmyJCRGTxuyBEJVvtPidN1KZ9mGc628fgms193ZuNXDz3XA78fMiyeS3OzVnLw2hkmgLmugGRlAboa8JUjgGXBfr3VEIQUtvVvgzR9vnHSzcyCWZTFJEBhbwzqzBPoe1HX+S82PZaI+cPeVrI6/31vBsBZl7cOznpEJLyMZQob4B0ok=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
