travis:
  secure:
    BINSTAR_TOKEN: CYtxmjnXMcukGb1+xEN8s4U/JMJv/TBBDrAQK0z99NOYpCl5qvM2rFk23wtYk/UtL3Em0XgtdosS6cqjFX7Z0i6SYHa3o8bmaO86Qkp9Sabxz4ArZU5t4Ikb6Tlok/LPLC9W6pKFzIv2X8EBPNWpnjJK3xewx9H5cZKK2lNRPsnA2FlACjO4bP97y+9BuihiHfl8peFw3OQcUnkydoCDFrugF6BEY7I9XQC1hqcaBzUcQnOge6NqsI2/bwm9vDyVd/V2Vi+eVBfLQmeuEQYCb05VB2KP91PArRBc6sWYaH0IUt1g1lj/bHDGeV6ErW4UpfA5VT6HQeErUT+QHGLGi6eN89Ea4rM4mB7k4Se8J+ubtzwLZTVqRGlBMieQAf6SKRxrSxoJO9qVzy05McRTM2NIzelxpZaeJGUy6+xr2d2tS61OyKowP7bvPtiDzSRe/bh6M7VXaklg7+nJaOr9buEAOx1xmkP+MLfRG+qk99ZCfF2Xu/rR4CO9l4p16tcV24nMS9x1T4zjmR/Y7YJhvyVODxQWVT9kvgbvV/eb/d8uZDZZfpq5Kl1mhVCqjHT8op1oMNXtxHGrGR1RIgq0EAjZisCd7NWSFEZJFilPO8bicMjwM3OgmQszWSSjG7f1CMmtyyvMLayiEvIE6g3FA2HTRLeyc/vicLXt+V6fG30=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
