travis:
  secure:
    BINSTAR_TOKEN: J1dwKZucQoRl4JxEfB5489kS5+5r88+342jPdQ8xpDWfqVJi8Y5+Qy3uaASmvjnRtBuDA1JtuBtWIsSOjZ6ZNcrfBpcjy+nWgTZsU+wwqCVkdgwZqbWPZ5togb7YL3G15/KWTkp6qxmM6JpXs7ns4zqzwt7UdB78Dp73ENkubk+gtQTeBUYPaP7PMZtHv/HsF9iy16i+NCeIvhiSUkCXhqDAnrJcA6lxswped+cfqw7ahaiA2Wv+kGlODUqs34r4jJbnd+BcNZ9dAh96KOe+0/O0c5ITwip83U1O5oDdDgOHC1ALpgRyD8KYZXmEx0vW86i01VxiBF2i/+y6ZBcwtfFJl17pmgVhJRGhAxV06YGYikYWeVxtuZZdvbTNXmZFfKZr3sNwYGBg0kc+5BmlRAta3h7qVzXLWjjRGOLu/A3swEENGzG/gjqyFS3l9Pd3qH1kQ3telSJMwO9fnSq4Xtvwg6xJPnzGxHLV0ImSzji8GoijKR/vxxWgL+GwEE8q5kf2jQ93JjyRGihwsSv+em9jJdgNDaPVpY1srQT7FSmPcLrQUDNu5ysjGGyWy1o64T+E2+rST7RoewG5FhHViAUn/ZRjjxHF+k5YWyidbMGKX0Sxzfbx/FSP9tRIVY/xAH7mO5y2YWrck429niKCvuoHJIZWJuPUWatncJMLgek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
