travis:
  secure:
    BINSTAR_TOKEN: qnH3kNX1hryXyp+k1hCJqQQF5XQj2JudSFvGtdxXAqFtxoNdQchxRjhA0fhTdJnCHZYstotZYHwS6SUl39tBGJrGZu5LhB3fLpW6iWu47ao86bR28ZNLJYrCL8LyRxjIfTgJKzncx+MZCkFPsqZNVyiIvOb42dZyZf8Xjru8T349Z/axaIP1TYrvyPzk1gebwpVNIejRW0sxBIPThEonVFn1BEzeimcNyLWQcGUXZloVP79kg3geHPQWtwTBarWJiK6Et8UeCZKn3el1ARp35x5ZiBmOJxfHgNxRu2wq0lxd2hasjCVtJUzSIaXsXL+lU3zFgzBWyc3devCu0o97YmyWHkvgUQftggRV+7cFdbW/gXdYx7JkdAy7dviRtLQ2scHMr3nipsjKZp9sH44b0jZT7lSnQHbkBp3jFcs+1HZV28YJk73qxHpL1TzZ9dUC3r6x+QP11wZOiTuG/5TWyxoVK05t9GGYVDHqVaQLye6fZLfZHBeB4eAP6tXXZtzaaag011OvWEOunS1SK8lbg8k6kEOAkbGX4Vbk6gVAdwuxbqnLjGeroa6tlwVF9pyWyRrY72o7t8KWRxdjWaIBCNzek2StGw1fKyJD9sKP8ZM9H3w7ZBEYydAt0mZIkh1tx1UMemSl5oZ4xcPw048c5Fys/PLl3JyiFJjAw2DPPMo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
