travis:
  secure:
    BINSTAR_TOKEN: ICXTkyLq7QofyVk4vnX4hvG0mlRVc8TybtY+KnNE/G3NYXULYC0dDFdQbAFzLFEXsUViOYal3/4cRBCX5lKq2kMbPdFv63D0wP6ILOyE3gFNTS9Azanxch/G8NkgazJIFmcQPGKKJWBQOoCdJ2gTYqZHLdUC4ivg1zsDqNCWEPwDCc7rRTUbXGDenYee8zNfLKZY3N3v2j88ksW1bUr4RacvDv971Sboni95Krb2F1p3SemkKL3BSXz1EZEQ9cB7LOCWpgFjC9/aT4MnNJXdlADuLTCVA16ue9QDnXMgPDEg5nGrLg5FHnsidJ1eDhXQpde8uYQj+H+AnFSLezu2Au8CMfZ6uL8GhbVMvBO7hMa3ukWcohw7PYSJm1FV6OCnn2Z1STsGbO8Ocy8oH/3sOSSwr4vNkCtlXMdh2vWiTj1UlLZyjjxIqhN+qVuuKUxxHp/Naj8uR6YW++XUPhDI8UUDlnu4GAwIniv8sHn6nBsxWeVC8Mi+N6XwVmp8Ks93PXBOAF15z0sqbby1Jv4PE1Aw0uSdW4Q6z0kP5B6+ihRcBn4ZZDakuIw3OLpWopY4vyGIfpQxAPMZhrXxA4Ug3ujqT0FKYYCNShgjzHDq1fuT/oUu66zmvJwuG2FMwbeGBkZIBv8yxwCmASGDZs+TPQUBfEi9oZ42/+iuYbrQFng=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
