travis:
  secure:
    BINSTAR_TOKEN: FsSZZ48KDX71N9ojbbCOX/63HXTzKq+CWhIxXORgQCrxd3AcqKvTKuuYwsYy050HkkVce2+Uv8Ey+kDIANfBHbyPicSDsZSewYF9rQnuAi9Naa8v2fxrWOslJ1wHn6wVazJoOz3fvjk1DCTiSxaJNYqBZ9puhDewQpFej2Jy2K8laShKYU0Q6vLJt6gxOdy5TDg0QKv7rzB/SKRa086h1Y+MRYTgRLUdCnIoeDs5OIf1uXnkjEirA+hkNF1j4iUMkaJjcKCSrfCaiwfvWt1BcLwi0Tm/z1xu8yqoLZKX950M5pDGd4PprDqMvUN0n3YGlwCV5Xe764vBYAwEG6a42t90SDwhxLHE0s/O4ORlKHblY9cco8wGVRM0g5/vyDO/8zAaVxcbfP2fnGGhcuRwPFHpAzavpuaY7ZmClKotd8zOnUAsJsGaDS0nNefpFO5YU2Ngm3cGgQFurbnVV6Rk2AhFGJD5vN/KPHOcAow+zmqbjGNCqOMGFwXIFaaZe4ts+ipV+oDV1vZhvb5WpoYJEWYoIfNIrkRZYuVP0nP6uW9SgB6YtHnq+eOtd/MUWSeOb5hKrPymISFWorhrRerhYUQMRyTvQ+ObB7kmM5LuXd8hD7OjPApMfyI/9xk7ho4w+uMlpIXY9CnO6KoGICfYVNLnuh3We3jZE64VtaMTW5E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
