travis:
  secure:
    BINSTAR_TOKEN: f3gFrOIG5LRPFQtJSmBe5GUneh87zSNdiWhBzvuY/8chW73mwE4R7j0swuR7CB+EZ5TpUjqw5F3xR8x2egwSZX7yXZU4vXLH41BXaity6oeXrreixJuwAfaulNdLuuB1OOf222m3Y9yiNg5WB4L9rbi+88M3N3HFvGuTII5P6yYMaJyK/8x327R/ltqEb2ZfCgWQk8NpceoXgRIDeEQVEgd1b/oIVdYBfr1tFto3rnxMm3MH5qJXgkDlcGWceLVdv20gUgdtRUHYfAa2eCby72aII556o3Orj+UrGY/d251LnLQddM1GiNe9YQPogZ3AR02SZaaza5siou4w2rgbxhlXkrg81H48+6R+7P8sRUzP7DiiAYJInLcFjiD6buFQ459typkqtYPL2OLu/ognObHBqxLjcstevu6ioCboonbu2vSVtnybfp1bop4OOSdKNUDJfjeFthUSBseBLjExxb47uBoU8Jrg5Uh7CktQ3Tjkp2cMDebRBxUIwDGqLy/31xj6BekbQiRHJpIWwoiDFFyD+OuqKVgZSkEBXygHBaK3fPRANn1XH+LbPVI1JrLjJDaxtFkEgivulVDvX8IoNHimZ6q+dREDN9b9q7qJJ4ZYgN4YBsRbuHvDLn6ycbsrWYgk57dWPPLiog+yVKzA5MZezcXsfmemuSqM34edqgU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
