travis:
  secure:
    BINSTAR_TOKEN: okWawc0bDq221NRp0a29smgTHKka/WcNBi0PbmsarF4vYb/wJcMwadblmC13sEwwfRBiIwk4sA9NqLeDgCLrazbJ0rxEjWOTnjzAyD93HNwqtXDH+uBUj2gB6a5PU/phFzVKQq7UpRfg+e/oCMVVqtr8ZRlHGSXt+6O/5Q/sRCghztRCfUAOS+sx17PYsdIODOu/oX6XWjCZEDXkoOmp1xcr+jlWWmbjcIvjxMnxsB4akE58A3vR644Y/b+HGvTsAuQERWkSCZNgZjXpcX5nO7VeHTEnzukJlL8QXuN4wwePcBzmGtdYOP/Bs52od3H+a18R9qEAVnaWmbgMdfjO0hOARHFeDokF/SOh7f/E2KFNE1MG0DVx/pXoD/59gvktEPjb28pB6NHBqTMPMWppJKX/Gf5onWgl72aGyg06c04JvghXkR7fjT9xAU3mhRv14j9Ejq2q+hFgtyZbi59ChWdVGh275UmOFDt1SO0TttcSCg/3/78P1Uan4FikcAAGcPvdNmKZbIhI7ZuTJMfkp20zd+wD0YIehAeEWAfpsuNLLv6B5nLhHDTQ546h72JWihYMbCd+sB+Xeci69IimBSV0BzW/u+zml6GSHDEY749pA7Ms1WEImURD31Q3jmXpRV5aEs+45xYm6XpBQ63eTSeFsoxxclZkBXEfhZaMiN8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
