travis:
  secure:
    BINSTAR_TOKEN: kgQyqaR9blu0TAykDxGvdEz0IXQ1A7vGv0dsYakHOsdJ3WePSCs+huxKQF0Uj+zUBUgjtIjXPztzdzxLCuD7pi6VmDaVolFJ5AzPCoOib4ZhKT0dkq/lM+yc7ohhrh1M0eqscUlIfvFRjAyIUbif2IUKLE8y/LvjNJWS3CjImwx48FYkZfAfTOUD96jjnBVzOpxqeGq/PD+SWK9TNM0Qg9nWpRj2ysLEzXv71YcPsOpuGjsDBO7t1Fo9Me4igNMHVv0w7SuLQGytRdL6MWUjdM5nGoHuxX/tcB5cCsPgaXm+pnTT/T8m5r30B+4cHYHo28bXUOF/QN/k1kzwrPUuSrH/mxV/ACoMpW6tiCyz3FDBKxAW9ZqxylRsgUSVHSW8hEzyTXE1ih/S2VQU6xcA9ySmyMzTli1UaevBUqP9v7/9MRmgws5UGjLWBis7HgGQ3NfHJjsOfvmQDE/qkrjDINjjyrTgMZvlSYY0enNgB/q3fyLBryDfEXxe+sKUIsdV2kF3T31u2Ir++sQXdYSjwcGU+1ombSzM5UaRCLjq6MxX6W2E/tiSI3Lk0ODJWtNqxv4/6krw6H0G7eEKAp+PON510+R9P/jYWj5JI8TLU0xXrbawzgbE8RkTUC8IwRVsVF8T2A3/3p1p5NilIZ8yv1aE8V1NEWe+J7idlQZ3L0o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
