travis:
  secure:
    BINSTAR_TOKEN: WJ67qudv5PEo02bdk2zPrv6FMu+RPxiWLakOoOV9i4p2+7qEyxmkbGmpC036xyYb2gMTk/4bCouapsWXzDcXJ5/kIF7VLXeVtRU0m01RvSsY3jQS1npzwbWHejGHsWmrq/hE2blaF0OjWvryjRql6QZ0Zw9sCsPcA0xsjK4JxJrZS48mpitejfDC9xIjAWZ6PaQ28qFfifHyy7jQpPNu1WVwt06tu2x7YELbIFkoqiR0sDr9iQZjk//TVVDFHJ4VNJN427JnvMjx2Xq94r4DCYpphhqRdqwpOrG78ZQ6fSqN7HcthHecKJvm3IFx+DyN0sq+F1Kt0wHicmSBogUY3G9wcbr6QCssRTgBYCOZU6yMMgbmXcAFpMFXZSXfvMtXqfGOcPmqtWnCkveOid5ocJNGNYqz8CG87TFLpvYZKdJBryaiRUzmezSLCgpPq0wLC/yuaAm/tIRov4kjMYel16BDD0kznYT5Un3f0ZntgMK5jlq9EesHy/cz+0rMMKal5tsaKrGJpfvrE3m+WVXtFvwi2XMdsgtgPX75g4sqXOZBfaC7Cvbn95jEcsOjG0489iWjwvhVgR6iMrBYH+oHBHTeYrAL75v79GDIvUCuLFJylZh9CkS+nE3lpDn5vfJJS3F0/N2eiLKiitI10vDz9QiotkzMHnLL2BhuOiwwAwA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
