travis:
  secure:
    BINSTAR_TOKEN: O+r+6He/Ojk6sbaT0AozevMwh1WAdIc6FhE8EljdtCVyo9TB8kRttPtDXoW364Z+4NwkjVSVMxAWzv4yhgrAF2f/ux78g36XAVnVs3g5LEckbeKdhqFC6e5Pvg1X6U4rOD8VFx8qvwnArFTDusnfPZM0ZvNIM4xCUaIat80Xb4KOPjIQ1aCJW0hmQnmexVYviCrz/oR++/yLrZ6YO20HTc1nH6numwvHxc4cKvO2LNQZ7T+Z4FXjXORzJgBCMzgH2S2rGbnpp0cZxHJCCz7/wpk0hMxoX4OFTwtyxJAYBfnbEyEQmtZjkpQixTh4qsC9ylI1i6uM1KeZrIW8mArqpxqAF3hIBBJuUDKDNUnTdZmLVA7jVYXHaj+sSgOxnrktMWVXPUuZlHZOagDZ73dCvS2oVnZ4fEaY7nDj/sY/BKD9oNXBCWWG374Vj5DQcRYWwG2jmLQyLqn4W0m/vSRpd3aRelHj8SfoLi4CnqXcz5KoxjNKy7/PnLfmNhdpy7hPmBYaJSMVz9T0z4uQV4JTHxxMIYrLliR9T1NLlZuTA9jSiHX250LcZ5NE+HBwg6DeTWM21Dlm7jIM8Hg5TdELkMet9YJKcLkRocug0U6nckSPttGJWHpIGz1BBwGvW5+p1P3TGseJwJH5YRtqrTSDZ52DeDN2veuBXQ7YCenifOc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
